In [ ]:
import pandas as pd

In [9]:
file_path = "../../withe-finance-ingest/Cuenta Corriente PESOS 29-07-25.xlsx"
# leo el excel y lo convierto en un dataframe
df = pd.read_excel(file_path, sheet_name=None)
# obtengo el nombre de la hoja
sheet_name = list(df.keys())[0]
# obtengo el dataframe de la hoja
df = df[sheet_name]
# impritmo el tipo de dato de cada columna
print("Tipos de datos de las columnas:")
print(df.dtypes)
# muestro las primeras filas del dataframe
df.head()

Tipos de datos de las columnas:
Liquida        datetime64[ns]
Operado        datetime64[ns]
Comprobante            object
Numero                  int64
Cantidad              float64
Especie                object
Precio                float64
Importe               float64
Saldo                 float64
Referencia             object
dtype: object

,Liquida,Operado,Comprobante,Numero,Cantidad,Especie,Precio,Importe,Saldo,Referencia
0,2024-07-24,2024-07-24,RETENCION,998986,0.0,NaN,0.0000,-152.32,4847.96,RET GGAL
1,2024-07-24,2024-07-24,DIVIDENDOS,972599,0.0,GGAL,0.0000,2147.03,6994.99,GGAL BYMA
2,2024-08-07,2024-08-07,RECIBO DE COBRO,1260985,0.0,NaN,0.0000,147800.00,154794.99,CREDITO CTA. CTE.
3,2024-08-09,2024-08-08,COMPRA NORMAL,6876896,15.0,DGCU2,1329.2640,-19938.96,134856.03,NaN
4,2024-08-09,2024-08-08,VENTA,6877008,-16.0,CVH,4557.7875,72924.60,207780.63,NaN

In [16]:
# si liquida y opera son tipos de datos, de tipo fecha, continuo
if pd.api.types.is_datetime64_any_dtype(df['Liquida']) and pd.api.types.is_datetime64_any_dtype(df['Operado']):
    print("Las columnas 'Liquida' y 'Opera' son de tipo fecha.")
# Si las columnas anteriores tienen el formato YYYY-MM-DD, imprimo True, sino Imprimo False junto con el formato actual
if df['Liquida'].dt.strftime('%Y-%m-%d').equals(df['Liquida'].astype(str)) and df['Operado'].dt.strftime('%Y-%m-%d').equals(df['Operado'].astype(str)):
    print("Las columnas 'Liquida' y 'Opera' tienen el formato YYYY-MM-DD.")
else:
    print("Las columnas 'Liquida' y 'Opera' no tienen el formato YYYY-MM-DD.")
    print("Formato actual de 'Liquida':", df['Liquida'].dt.strftime('%Y-%m-%d').unique())
    print("Formato actual de 'Opera':", df['Operado'].dt.strftime('%Y-%m-%d').unique())

# Si los valores de columnas Comprobnante, Especie y Referencia no tienen espacio al principio o al final
if df['Comprobante'].str.strip().equals(df['Comprobante']) and df['Especie'].str.strip().equals(df['Especie']) and df['Referencia'].str.strip().equals(df['Referencia']):
    print("Las columnas 'Comprobante', 'Especie' y 'Referencia' no tienen espacios al principio o al final.")
else:
    print("Algunas columnas tienen espacios al principio o al final.")

# Si las columnas Numero es de topo entero, continuo
if pd.api.types.is_integer_dtype(df['Numero']):
    print("La columna 'Numero' es de tipo entero.")

# Si las columnas cantidad, Precio, Importe, y Saldo son de tipo float, continuo
if pd.api.types.is_float_dtype(df['Cantidad']) and pd.api.types.is_float_dtype(df['Precio']) and pd.api.types.is_float_dtype(df['Importe']) and pd.api.types.is_float_dtype(df['Saldo']):
    print("Las columnas 'Cantidad', 'Precio', 'Importe' y 'Saldo' son de tipo float.")

Las columnas 'Liquida' y 'Opera' son de tipo fecha.
Las columnas 'Liquida' y 'Opera' tienen el formato YYYY-MM-DD.
Algunas columnas tienen espacios al principio o al final.
La columna 'Numero' es de tipo entero.
Las columnas 'Cantidad', 'Precio', 'Importe' y 'Saldo' son de tipo float.